import {
  displaySimpleWindow,
  closePopupWindow,
  displayWindow,
} from "../scripts/popupWindow.js";
//==================================================================================
// start of AI chatbot
//==================================================================================

// DOM ELEMENTS for the AI chatbot to be used in the functions
const sendBtn = document.getElementById("sendAiMessage");
const chatInput = document.getElementById("aiUserInput");
const chatWindow = document.getElementById("aiChatWindow");
const sidebar = document.getElementById("aiSidebar");
const openBtn = document.getElementById("aiToggleButton");
const closeBtn = document.getElementById("closeAiSidebar");

//=========================================================================================
// This function creates and displays a chat message bubble in the sidebar,
// applies different styling/alignment depending on whether the message is from the user or the AI assistant,
// then appends the message to the chat window and auto-scrolls to the latest message.
//==========================================================================================
function appendMessage(role, text) {
    const msgDiv = document.createElement("div");
    // change the class string to "chat chat-end" if its users and to "chat chat-start " if its ai

    msgDiv.className = `chat ${role === "user" ? "chat-end" : "chat-start"}`;
    // create and insert the chat bubble with the message text, but for user assign an orange bg with white text

    msgDiv.innerHTML = `<div class="chat-bubble text-sm  ${role === "user" ? "bg-orange text-white" : ""}">${text}</div>`;
    chatWindow.appendChild(msgDiv);
    chatWindow.scrollTop = chatWindow.scrollHeight; // chat box automatically scroll to the bottom
}

//=========================================================================================
//This function handles the AI’s response AFTER it comes back from the server.
// Generated by Gemini, replaced the parts for appending food items to match with our UI
// @author https://gemini.google.com/
//==========================================================================================
function processAiResponse(rawText) {
    // Check if the response contains the [UPDATE_FORM] command
    // means AI wants to update the form
    if (rawText.includes("[UPDATE_FORM]")) {
        const parts = rawText.split("[UPDATE_FORM]");
        const textToDisplay = parts[0]; // The friendly message
        const jsonString = parts[1]; // The actual form data
        // Shows AI message in chat UI
        appendMessage("assistant", textToDisplay);

        try {
            // regex method - Find everything from the first { to the last } in the json response
            const jsonMatch = jsonString.match(/\{[\s\S]*\}/);
            if (!jsonMatch) throw new Error("No JSON object found in response"); // Manually creates an error
            const data = JSON.parse(jsonMatch[0]); // Converts text into real JS object

            // Fill standard text fields
            if (data.title) document.getElementById("editTitle").value = data.title;
            if (data.location) document.getElementById("editLocation").value = data.location;
            if (data.price) document.getElementById("editPrice").value = data.price;
            if (data.description) document.getElementById("editDescription").value = data.description;
            if (data.contact) document.getElementById("editContact").value = data.contact;

            // Handle Categories (Checkboxes) - check if they exist and if category is an array
            //   this check is necessarry because AI might send a string instead of an array
            if (data.category && Array.isArray(data.category)) {
                const catMap = {
                    Produce: "editProduce", // the values are the ids of the checkboxes in html
                    Meat: "editMeat",
                    Dairy: "editDairy",
                    "Baked Goods": "editBakedGoods",
                    "Cooked Meals": "editCookedMeals",
                };

                // Clear existing checkboxes first if needed
                // Object.values(catMap) pulls out just the values of catMapt which are ids
                Object.values(catMap).forEach((id) => {
                    const el = document.getElementById(id);
                    if (el) el.checked = false;
                });
                // data.category is the array from the AI, e.g. ["Produce", "Dairy"].
                //  For each name, it looks up the corresponding checkbox ID in catMap, finds it in the DOM, and checks it.
                data.category.forEach((catName) => {
                    const id = catMap[catName];
                    if (id) document.getElementById(id).checked = true;
                });
            }

            // dynamically build food bars using the AI's foods array,
            //   mirrors what addFood() does but without the popup
            if (data.foods && Array.isArray(data.foods)) {
                const foodsList = document.getElementById("foodsList");
                foodsList.innerHTML = "";
                foodArray = []; // reset the global food array, because AI is going to replace it when user interacts with it

                data.foods.forEach((item) => {
                    //The || 1 is a safety net — if the AI sends something which is not an int, it defaults to 1 instead of crashing.
                    const quantity = item.quantity || 1;

                    foodArray.push({ name: item.name, quantity: quantity });
                    const index = foodArray.length - 1; // after pushing each item capture the index to work with minusQuant or plusQuant

                    const foodBar = document.createElement("div");
                    foodBar.innerHTML = `
            <div class="flex justify-between rounded-lg text-light-brown border-[#9b9b9b] border-solid border">
              <div class="py-2 px-4">${item.name}</div>
              <div class="flex">
                <div id="minusQuant" class="py-2 px-6 border-[#9b9b9b] border-solid border-l">-</div>
                <div id="itemQuant" class="py-2 px-8 border-[#9b9b9b] border-solid border-l">${quantity}</div>
                <div id="plusQuant" class="py-2 px-6 border-[#9b9b9b] border-solid border-l">+</div>
              </div>
            </div>
          `;

                    let qty = quantity;
                    const itemQuant = foodBar.querySelector("#itemQuant");

                    foodBar.querySelector("#minusQuant").addEventListener("click", () => {
                        if (qty > 0) {
                            qty -= 1;
                            itemQuant.textContent = qty;
                            foodArray[index].quantity = qty;
                            if (foodArray[index].quantity === 0) {
                                foodArray.pop();
                                foodBar.remove();
                            }
                        }
                    });

                    foodBar.querySelector("#plusQuant").addEventListener("click", () => {
                        qty += 1;
                        itemQuant.textContent = qty;
                        foodArray[index].quantity = qty;
                    });

                    foodsList.appendChild(foodBar);
                });
            }
        } catch (e) {
            console.error("Failed to parse AI JSON:", e);
        }
    } else {
        // Just a normal conversation message
        appendMessage("assistant", rawText);
    }
}

let chatHistory = []; // Initialize outside the function to maintain state

//=========================================================================================
//This function Handles sending messages to the AI assistant by collecting the user's message,
// current form state, and chat history, then processing and displaying the AI response.
// Generated by Gemini
// @author https://gemini.google.com/
//==========================================================================================
async function handleChat() {
    const message = chatInput.value.trim();
    if (!message) return;

    // Display user message and clear input
    appendMessage("user", message);
    chatInput.value = "";

    // Show loading state
    const loadingId = "ai-loading-" + Date.now(); //creates a unique id
    const loadingDiv = document.createElement("div");
    loadingDiv.id = loadingId; //assign that unique id to created div
    loadingDiv.className = "text-xs text-orange italic ml-2 mb-4";
    loadingDiv.innerText = "Pantry Swap is thinking...";
    chatWindow.appendChild(loadingDiv);
    chatWindow.scrollTop = chatWindow.scrollHeight; // automatically scrolls the chat to the bottom

    // Scrape form data to let the AI know what's already filled
    const formData = {
        title: document.getElementById("editTitle").value,
        location: document.getElementById("editLocation").value,
        price: document.getElementById("editPrice").value,
        description: document.getElementById("editDescription").value,
        contact: document.getElementById("editContact").value,
    };

    try {
        const response = await fetch("/api/chat", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            // ADDED: Sending chatHistory along with the message and form data
            body: JSON.stringify({
                message,
                formData,
                history: chatHistory,
            }),
        });

        const data = await response.json();

        const loadingEl = document.getElementById(loadingId); // Find the loading div again using its ID and removes it
        if (loadingEl) loadingEl.remove();

        //Checks whether backend returned text
        if (data.text) {
            // Save both the user message and AI response to chatHistory
            // This prevents the AI from repeating questions it already asked
            chatHistory.push({ role: "user", parts: [{ text: message }] });
            chatHistory.push({ role: "model", parts: [{ text: data.text }] });

            processAiResponse(data.text);
        } else {
            appendMessage("assistant", "Something went wrong. Please try again.");
        }
    } catch (error) {
        const loadingEl = document.getElementById(loadingId);
        if (loadingEl) loadingEl.innerText = "Error: Connection lost.";
        console.error("Chat Error:", error);
    }
}

// When the user clicks Send button or presses Enter, run the chat function.
sendBtn.addEventListener("click", handleChat);
chatInput.addEventListener("keypress", (e) => {
    if (e.key === "Enter") handleChat();
});

// Open the AI chatbot
openBtn.addEventListener("click", () => {
    sidebar.classList.remove("translate-x-full"); // // element slides into screen from the right
    openBtn.style.opacity = "0"; // Makes open button invisible
    openBtn.style.pointerEvents = "none"; // Disables mouse interaction with button.
});

// Close the AI chatbot
closeBtn.addEventListener("click", () => {
    sidebar.classList.add("translate-x-full"); // element slides completely off screen to the right
    openBtn.style.opacity = "1"; // Makes open button visible
    openBtn.style.pointerEvents = "auto"; // Enables mouse interaction with button
});
//==================================================================================
// end of AI chatbot
//==================================================================================

let foodArray = [];

//==================================================================================
// This function fetches user's data from the database and converts it to json
//===================================================================================
async function loadUserData() {
    const response = await fetch("/user");
    const userData = await response.json();
    return userData;
}

//==================================================================================
// This function pre-fills location and phone field in the form based on the data
// available in the database for the user
//==================================================================================
function prefillForm(userRecord) {
  const fullAddress = `${userRecord.address}, ${userRecord.postalCode}, Canada`
  document.getElementById("editLocation").value = fullAddress || "";
  document.getElementById("editContact").value = userRecord.phone || "";
}

//==================================================================================
// This function initializes the page by loading user's data and pre-filling the form
// based on that information
//==================================================================================
async function initializePage() {
    const data = await loadUserData();
    prefillForm(data);
}

initializePage();

const form = `
<form id="food-form" class="flex flex-col gap-4 mt-4 text-start">
  <div class="flex flex-col gap-1">
    <label>Name</label>
    <input type="text" name="name" placeholder="Gala apples" />
  </div>
  <div class="flex flex-col gap-1">
    <label>Quantity</label>
    <input type="text" name="quantity" placeholder="2" />
  </div>
</form>`;

const buttons = [
    {
        label: "Add food",
        color: "box-color-0",
        hover: "hover-outline",
        onClick: addFood,
    },
    {
        label: "cancel",
        color: "box-color-1",
        hover: "hover-outline",
        onClick: closePopupWindow,
    },
];

//============================================================================================================================================================================
//The addFood function takes the data entered by the user in from the Add Food form and creates a new food bar display with that information. 
//Event listeners are then added to the plus and minus quantity buttons to listen for clicks. It triggers the text displayed to update and the quantity of food in the foodArray
//If the quantity gets reduced to 0, then food item itself gets removed.
//============================================================================================================================================================================
function addFood() {
    const foodForm = document.getElementById("food-form");
    const formData = new FormData(foodForm);

    let isValid = true;

    for (const [key, value] of formData.entries()) {
        if (!value.trim()) isValid = false;
    }

    if (isValid) {
        const foodsList = document.getElementById("foodsList");
        const foodBar = document.createElement("div");

        foodBar.innerHTML += `
    <div id="foodBar" class="flex justify-between rounded-lg text-light-brown border-[#9b9b9b] border-solid border">
        <!-- left -->
        <div id="" class="py-2 px-4">${formData.get("name")}</div>
        <!-- right -->
        <div id="" class="flex">
            <!-- minus -->
            <div id="minusQuant" class="py-2 px-6 border-[#9b9b9b] border-solid border-l">-</div>
            <!-- quant -->
            <div id="itemQuant" class="py-2 min-w-16 text-center border-[#9b9b9b] border-solid border-l">${formData.get("quantity")}</div>
            <!-- plus -->
            <div id="plusQuant" class="py-2 px-6 border-[#9b9b9b] border-solid border-l">+</div>
        </div>
    </div>
    `;

        const itemQuant = foodBar.querySelector("#itemQuant");
        let quantity = parseInt(formData.get("quantity"));

        foodArray.push({ name: formData.get("name"), quantity: quantity });

        foodBar.querySelector("#minusQuant").addEventListener("click", () => {
            if (quantity > 0) {
                quantity -= 1;
                itemQuant.textContent = quantity; //update display
                const currentIndex = foodArray.findIndex(food => food.name == formData.get("name")) //find the current index of the food even after updates
                
                foodArray[currentIndex].quantity = quantity; //update array

                    if (quantity == 0) {
                    foodArray.splice(currentIndex, 1);
                        foodBar.remove();
                    }
            }
        });

        foodBar.querySelector("#plusQuant").addEventListener("click", () => {
            if (quantity > 0) {
                quantity += 1;
                itemQuant.textContent = quantity; //update display
                const currentIndex = foodArray.findIndex(food => food.name == formData.get("name")) //find the current index of the food even after updates
                foodArray[currentIndex].quantity = quantity; //update array
                
            }
        });
        foodsList.appendChild(foodBar);
        closePopupWindow();
    } else {
        if (foodForm.querySelector(".form-error")) return;

        const error = document.createElement("div");
        error.className = "form-error text-red text-sm";
        error.textContent = "Required fields missing";

        foodForm.appendChild(error);
    }
}

//add food button
document.getElementById("addFoodButton").addEventListener("click", () => {
    displaySimpleWindow("Add food" + form, buttons, false);
});

//cancel button
document.getElementById("cancelButton").addEventListener("click", () => {
    window.location.href = "/sell";
});

//=============================================================================================
// This function converts a File object to a Base64-encoded data URL for storage and preview
//=============================================================================================
// This function returns a Promise — meaning it's asynchronous work. Since reading a file takes time, we can't get the result instantly. The Promise will either resolve (success) or reject (error) when it's done.
function readImageAsBase64(file) {
    return new Promise((resolve, reject) => {
        //A safety check. If no file was passed in, bail out early so nothing crashes.
        if (!file) {
            return;
        }
        // FileReader is a built-in browser API specifically designed to read the contents of files that a user selects. Think of it like opening a file on your computer — but the browser is doing it for you.
        const reader = new FileReader();

        //onload is an event handler that fires when the file has finished being read. e.target.result contains the file's content — in this case, a Base64 string (a text representation of binary data, like data:image/png;base64,iVBOR...). When we get it, we resolve the Promise with it.
        //  .onload is not exclusive to FileReader, but it is a pattern specific to certain browser APIs.
        // e is the event object automatically passed in when onload fires // When onload fires, the browser automatically creates an event object of the FileReader instance and passes it in.
        // e.target is the FileReader instance itself (reader)
        // e.target.result is where FileReader stores the finished result — the Base64 string
        // or can be written like ... 
        // reader.onload = function() {
        //  resolve(reader.result)  // no `e` needed at all
        // }
        // these event listeners work just like .addeventlistener()
        // reader.addEventListener("load", function(e) {
        //    resolve(e.target.result);
        // })
        // event listeners aren't exclusive to the DOM, they can be used for anything that comes from a built-in interface called EventTarget.  FileReader isn't in the DOM, but it's still an EventTarget — meaning the browser gave it the ability to fire and listen to events.
        reader.onload = function (e) {
            resolve(e.target.result); // full Base64 string
        };

        //If something goes wrong while reading, onerror fires and we reject the Promise with an error message.
        reader.onerror = function () {
            reject(new Error("Error reading image"));
        };

        //This kicks off the actual reading. readAsDataURL tells the FileReader to read the file and encode it as a Base64 data URL. Without this line, nothing would happen!
        reader.readAsDataURL(file);
    });
}

let currentImg;
// upload image button
//Grab the "Upload Photo" button from the DOM and listen for clicks.
const uploadImgBtn = document.getElementById("uploadImgBtn");
uploadImgBtn.addEventListener("click", async () => {

    // listingImageUpload is the hidden <input type="file"> in your HTML. .files is an array of selected files — .files[0] gets the first (and only) one the user picked.
    const listingImg = document.getElementById("listingImageUpload").files[0];
    // Calls the helper function and waits for it to finish. Once done, encodedImg holds the full Base64 string of the image.
    const encodedImg = await readImageAsBase64(listingImg); // returns a promise, await unwraps the promise which reveals the image as a base64 string
    // Saves the Base64 string into currentImg (so it can be sent to the server later on form submit), and immediately previews the image on the page by setting the <img> tag's src to the Base64 string. Browsers can render Base64 images directly — pretty cool!
    currentImg = encodedImg;
    document.getElementById("listingImg").src = currentImg;
});

//=======================================================================================
// This function gets latitude and longitude coordinates from an address using geoapify
//=======================================================================================
async function getCoordsFromAddress(userAddress){
  const apiKey = `a55530eef54342eea72f8d09fc6f365a`
  const url =
      `https://api.geoapify.com/v1/geocode/search` +
      `?text=${encodeURIComponent(userAddress)}` +
      `&filter=countrycode:ca` +
      `&apiKey=${encodeURIComponent(apiKey)}`;
  const response = await fetch(url)
  const data = await response.json()
  if (data.error) {
      throw new Error(
        `Geocoding failed: ${data.statusCode || ""} ${data.error} - ${data.message || ""}`,
      );
    }

    if (!data.features || !data.features.length) {
      throw new Error(
        `Geocoding failed: no results found for "${fullAddress}"`,
      );
    }
  const result = data.features[0];
  const lat = result.properties.lat;
  const lng = result.properties.lon;
  const newObj = {
    lat: lat,
    lng: lng,
  }
  return newObj
}

//create button
document.querySelector("form").addEventListener("submit", async (event) => {
    event.preventDefault();
    //get back the updated values
    const updatedTitle = document.getElementById("editTitle").value;
    const updatedLocation = document.getElementById("editLocation").value;
    const updatedPrice = document.getElementById("editPrice").value;
    const updatedContact = document.getElementById("editContact").value;
    const updatedDescription = document.getElementById("editDescription").value;
    const updatedProduce = document.getElementById("editProduce").checked;
    const updatedMeat = document.getElementById("editMeat").checked;
    const updatedDairy = document.getElementById("editDairy").checked;
    const updatedBakedGoods = document.getElementById("editBakedGoods").checked;
    const updatedCookedMeals = document.getElementById("editCookedMeals").checked;
    const updatedImage = currentImg;

  const addressData = await getCoordsFromAddress(updatedLocation)
  const updatedLat = addressData.lat
  const updatedLng = addressData.lng

  // //validate required fields not left blank
  if (foodArray.length == 0) {
    displaySimpleWindow("Please add a food item.")
    return;
  }

    let updatedCategory = [];
    updatedProduce == true ? updatedCategory.push("Produce") : undefined;
    updatedMeat == true ? updatedCategory.push("Meat") : undefined;
    updatedDairy == true ? updatedCategory.push("Dairy") : undefined;
    updatedBakedGoods == true ? updatedCategory.push("Baked Goods") : undefined;
    updatedCookedMeals == true ? updatedCategory.push("Cooked Meals") : undefined;

  const response = await fetch(`/CreateListing`, {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({
      //seller is added in on the server.js
      title: updatedTitle,
      location: updatedLocation,
      price: updatedPrice,
      contact: updatedContact,
      description: updatedDescription,
      category: updatedCategory,
      foods: foodArray,
      image: updatedImage,
      lat: updatedLat,
      lng: updatedLng,
    }),
  });
  if (response.ok) {
    displaySimpleWindow("Created!", [{label: "OK", color: "box-color-0", hover: "hover-outline", onClick: ()=> {window.location.href = "/sell"}}])
    ;
  }
});
